version: '3.3'
services:
    app:
        depends_on:
            - mysql
        build: ./api
        env_file: .env
        restart: unless-stopped
        ports:
            - '3000:3000'
        command: npm start
    mysql:
        build: ./mydb
        restart: unless-stopped
        volumes:
            - mydb:/var/lib/mysql
        environment:
            - MYSQL_DATABASE
            - MYSQL_ROOT_PASSWORD
        ports:
            - '3306:3306'            

volumes:
    mydb:
